---
title: "Introduction to RVIMP package"
author: "Robert Miltenberger"
output: 
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{Introduction to RVIMP package}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options:
  chunk_output_type: console
---


```{r, fig.height = 5, fig.width = 5, fig.align = "center"}
library(RVIMP)
data(RVIMP_sim_data)
RVIMP_obj<-RVIMP(formula=y~.,data=RVIMP_sim_data,Z = "all",residual.model = "Linear",keep.ranger = T,seed=42,num.trees=200)
RVIMP_obj
plot(RVIMP_obj,ask=F)
```


```{r, fig.height = 5, fig.width = 5, fig.align = "center"}
comp_obj<-compare_VIMP_RVIMP(formula = y~.,data = RVIMP_sim_data,residual.model = "Linear",seed=42)
comp_obj
plot(comp_obj)
```

```{r, fig.height = 5, fig.width = 5, fig.align = "center"}
RVIMP_test_obj<-test.RVIMP(formula = y~.,data = RVIMP_sim_data,Z="x1",alpha.one.sided = 0.05,reps=100,residual.model = "Linear",sample_seed = 50,seed=42,num.trees=200)
RVIMP_test_obj
plot(RVIMP_test_obj,ask=F)
```
